basic server implemetation
mikitachab/score-board pull request #3
Opened 2020-10-08 16:21 UTC by antonskwr

2020-10-08 16:28 UTC, mikitachab requested changes

2020-10-08 16:28 UTC, mikitachab commented on main.go
> +func port() string {
getPort?

2020-10-08 16:28 UTC, mikitachab commented on main.go
> +	log.Printf("Starting server on port%s ...\n", port())
maybe assign port to a var?

2020-10-08 16:31 UTC, mikitachab commented
also you add can info in description that PR is solution of #2

2020-10-08 18:27 UTC, mikitachab approved these changes

2020-10-10 13:23 UTC, vtev approved these changes

2020-10-11 12:21 UTC, merged