New framework
mikitachab/score-board pull request #35
Opened 2020-11-17 23:06 UTC by mikitachab

created framework for writing views. Key-points: 
- views now detached from server. 
- views take HandleCtx which provide data it's need
- now view easier to test. 
- also way passing template to render is rethink-ed

2020-11-17 23:55 UTC, antonskwr requested changes

2020-11-17 23:55 UTC, antonskwr commented on server/views_test.go
> +		t.Errorf("handler returned wrong status code: got %v want %v",
Maybe "expected" instead of "want"

2020-11-18 09:46 UTC, mikitachab commented on server/views_test.go
> +		t.Errorf("handler returned wrong status code: got %v want %v",
:+1:

2020-11-21 00:13 UTC, antonskwr approved these changes

2020-11-21 17:44 UTC, merged